% Example 2.3
% Use a large data set generated by randn to determine if these data have a Gaussian probability 
% distribution. Also estimate the probability distribution of the data produced by rand.
clear all;
close all;
clc;

% Função para calcular o histograma de um conjunto de dados
% [ht,xout] = hist(x,nu_bins); % Calculate the histogram of data in x
% where the inputs are the data set vector, x, and nu_bins are the number of bins desired. 

% Example 2.3 Evaluation of the distribution of data produced by MATLAB's
% rand and randn functions.
N = 20000;  % Numero de pontos de dados
nu_bins = 40;  % Numero de bins
y = randn(1,N);  % Gerador de ruido Gaussiano aleatório

[ht,xout] = hist(y,nu_bins);  % Calcula o histograma dos dados em y
figure(1);  % Cria uma nova figura
bar(xout, ht);  % Plota o histograma
xlabel('x');  % Rotula o eixo x
ylabel('P(x)');  % Rotula o eixo y 
title('Histogram produzido por randn');  % Adiciona um título ao gráfico
subtitle('Ruido Gaussiano Aleatório');  % Adiciona um subtítulo ao gráfico



figure(2);  % Cria uma nova figura
ht_norm = ht/max(ht);  % Normaliza o histograma
bar(xout, ht_norm);  % Plota o histograma
xlabel('x');  % Rotula o eixo x
ylabel('P(x)');  % Rotula o eixo y 
title('Histogram produzido por randn');  % Adiciona um título ao gráfico
subtitle('Ruido Gaussiano Aleatório Normalizado');  % Adiciona um subtítulo ao gráfico